/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ServiceAccountsRequestBuilderNavigationMetadata, ServiceAccountsRequestBuilderRequestsMetadata, type ServiceAccountsRequestBuilder } from './serviceAccounts/index.js';
// @ts-ignore
import { apiClientProxifier, ParseNodeFactoryRegistry, SerializationWriterFactoryRegistry, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Instantiates a new {@link SecureServiceAccountsClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createSecureServiceAccountsClient(requestAdapter: RequestAdapter) {
    if (requestAdapter === undefined) {
        throw new Error("requestAdapter cannot be undefined");
    }
    const serializationWriterFactory = requestAdapter.getSerializationWriterFactory() as SerializationWriterFactoryRegistry;
    const parseNodeFactoryRegistry = requestAdapter.getParseNodeFactory() as ParseNodeFactoryRegistry;
    const backingStoreFactory = requestAdapter.getBackingStoreFactory();
    
    if (parseNodeFactoryRegistry.registerDefaultDeserializer) {
    }
    
    if (serializationWriterFactory.registerDefaultSerializer) {
    }
    
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://developer.api.autodesk.com/authentication/v2";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<SecureServiceAccountsClient>(requestAdapter, pathParameters, SecureServiceAccountsClientNavigationMetadata, undefined);
}
/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface SecureServiceAccountsClient extends BaseRequestBuilder<SecureServiceAccountsClient> {
    /**
     * The serviceAccounts property
     */
    get serviceAccounts(): ServiceAccountsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SecureServiceAccountsClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SecureServiceAccountsClientNavigationMetadata: Record<Exclude<keyof SecureServiceAccountsClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    serviceAccounts: {
        requestsMetadata: ServiceAccountsRequestBuilderRequestsMetadata,
        navigationMetadata: ServiceAccountsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
